#! /bin/sh
#------------------------------------------------------------------------------
#$Author$
#$Date$
#$Revision$
#$URL$
#------------------------------------------------------------------------------

# Run a Grammatica-based BNF parser and report syntax errors. Return
# 0 on success, error code on failure.

# USAGE:
#    $0 input-bnf.txt
#    $0 < input-bnf.txt

SCRPDIR=$(dirname $0)
BASEDIR=$(dirname ${SCRPDIR})
LIB_DIR=${BASEDIR}/lib

if [ -e "${LIB_DIR}" ]
then
    TOOL_DIR=${LIB_DIR}
else
    TOOL_DIR=${BASEDIR}/tools
fi

GRAMMATICA_JAR=$(find "${TOOL_DIR}/" -name "grammatica*.jar" | head -1)

CLASSPATH=${CLASSPATH:+:$CLASSPATH}

CLASSPATH=\
${BASEDIR}\
:${BASEDIR}/generated\
:${LIB_DIR}\
:${GRAMMATICA_JAR}\
$CLASSPATH 

export CLASSPATH

cat ${1+"$@"} | java BNFParse
