#! /bin/sh
#------------------------------------------------------------------------------
#$Author$
#$Date$
#$Revision$
#$URL$
#------------------------------------------------------------------------------

# Run a Grammatica-based parser of a 'language', generated on-the-fly
# from the 'language.grammatica' grammar.
#
# A given input file written in 'language' ('input-file.language') is
# processed and syntax errors are reported. Returns 0 on success,
# error code on failure.

# USAGE:
#    $0 language.grammatica input-file.language

SCRPDIR=$(dirname $0)
BASEDIR=$(dirname ${SCRPDIR})
LIB_DIR=${BASEDIR}/lib

if [ -e "${LIB_DIR}" ]
then
    TOOL_DIR=${LIB_DIR}
else
    TOOL_DIR=${BASEDIR}/tools
fi

GRAMMATICA_JAR=$(find "${TOOL_DIR}/" -name "grammatica*.jar" | head -1)

CLASSPATH=${CLASSPATH:+:$CLASSPATH}

CLASSPATH=\
${GRAMMATICA_JAR}\
$CLASSPATH 

export CLASSPATH

GRAMMAR="$1"

shift

for FILE in ${1+"$@"}
do
    java -jar "${GRAMMATICA_JAR}" "${GRAMMAR}" --parse "${FILE}"
done
