#! /bin/sh
#------------------------------------------------------------------------------
#$Author$
#$Date$
#$Revision$
#$URL$
#------------------------------------------------------------------------------

# Run a Grammatica-based EBNF parser and report syntax errors. Return
# 0 on success, error code on failure.

# USAGE:
#    $0 < input-ebnf.txt

SCRPDIR=$(dirname $0)
BASEDIR=$(dirname ${SCRPDIR})

if [ -d "${BASEDIR}/tools/" ]
then
    TOOL_DIR=${BASEDIR}/tools/
else
    TOOL_DIR=${BASEDIR}/lib/
fi

GRAMMATICA_JAR=$(find "${BASEDIR}/" "${TOOL_DIR}/" -name "grammatica*.jar" | head -1)

CLASSPATH=${CLASSPATH:+:$CLASSPATH}

CLASSPATH=\
${BASEDIR}\
:${BASEDIR}/generated\
:${BASEDIR}/lib/ebnf\
:${GRAMMATICA_JAR}\
$CLASSPATH 

export CLASSPATH

cat ${1+"$@"} | java EBNFParse
